### ISSUE TITLE
Version 2.1.3 is not available

### ISSUE THREAD

**Issue by IgorGanapolsky** [HeinrichReimer/material-drawer#69] opened 2015-08-03 17:28 UTC
I am trying to use `    compile 'com.heinrichreimersoftware.materialdrawer:library:2.1.2'` in build.gradle, but it complains that this version is not available.  I think you should update your README file on this repo.

Thanks,
Igor

**Comment by HeinrichReimer** [comment] 2015-08-03 20:00
Duplicate of #68

**Closed by HeinrichReimer** 2015-08-03 20:00 UTC
